### ISSUE TITLE
There is no lotus field in config.toml.example

### ISSUE THREAD

**Issue by flyworker** [filswan/go-swan-provider#72]
port = 8888

[lotus]
api_url="http://[ip]:[port]/rpc/v0"   # Url of lotus web api, generally the [port] is 1234
miner_api_url="http://[ip]:[port]/rpc/v0"   # Url of lotus miner web api, generally the [port] is 2345
Show more
<https://github.com/filswan/go-swan-provider|filswan/go-swan-provider>filswan/go-swan-provider | Added by GitHub

j1v  3 minutes ago
aaaa they need to be in [lotus] section

**Comment by DoraNebula** [comment]
[lotus]
client_api_url="http://[ip]:[port]/rpc/v0"   # Url of lotus client web api, generally the [port] is 1234
market_api_url="http://[ip]:[port]/rpc/v0"   # Url of lotus market web api, generally the [port] is 2345, when market and miner are not separate, it is also the url of miner web api
market_access_token=""                       # Access token of lotus market web api, when market and miner are not separate, it is also the access token of miner web api

**Comment by boqian-nbai** [comment]
Lotus section added.
